//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello.ConcatenatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.mycompany.com/", ConfigurationName="ConcatenatorService.Concatenator")]
    public interface Concatenator {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Hello.ConcatenatorService.whoisResponse whois(Hello.ConcatenatorService.whoisRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class whoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="whois", Namespace="http://webservice.mycompany.com/", Order=0)]
        public Hello.ConcatenatorService.whoisRequestBody Body;
        
        public whoisRequest() {
        }
        
        public whoisRequest(Hello.ConcatenatorService.whoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class whoisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public whoisRequestBody() {
        }
        
        public whoisRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class whoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="whoisResponse", Namespace="http://webservice.mycompany.com/", Order=0)]
        public Hello.ConcatenatorService.whoisResponseBody Body;
        
        public whoisResponse() {
        }
        
        public whoisResponse(Hello.ConcatenatorService.whoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class whoisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public whoisResponseBody() {
        }
        
        public whoisResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConcatenatorChannel : Hello.ConcatenatorService.Concatenator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConcatenatorClient : System.ServiceModel.ClientBase<Hello.ConcatenatorService.Concatenator>, Hello.ConcatenatorService.Concatenator {
        
        public ConcatenatorClient() {
        }
        
        public ConcatenatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConcatenatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hello.ConcatenatorService.whoisResponse Hello.ConcatenatorService.Concatenator.whois(Hello.ConcatenatorService.whoisRequest request) {
            return base.Channel.whois(request);
        }
        
        public string whois(string arg0) {
            Hello.ConcatenatorService.whoisRequest inValue = new Hello.ConcatenatorService.whoisRequest();
            inValue.Body = new Hello.ConcatenatorService.whoisRequestBody();
            inValue.Body.arg0 = arg0;
            Hello.ConcatenatorService.whoisResponse retVal = ((Hello.ConcatenatorService.Concatenator)(this)).whois(inValue);
            return retVal.Body.@return;
        }
    }
}
